name: Automated Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven Tests
        run: mvn -B verify

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_IMAGE }}" .

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_IMAGE }}"

      - name: Trigger Render deploy
        run: |
          # Check required secrets
          if [ -z "${{ secrets.RENDER_URL }}" ]; then
            echo "RENDER_URL secret is not set. Failing workflow."
            exit 1
          fi

          if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then
            echo "RENDER_API_KEY secret is not set. Failing workflow."
            exit 1
          fi

          echo "Triggering Render deploy..."
          curl -fsS -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_URL }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json"
